Fix JSON-encoding issues with activesupport-6.0/ruby3.0
Fixes the problem where JSON.dump(o) calls `o.to_s` and complains about
TypeError: wrong argument type nil (expected String)

(cherry picked from commit 1f74d0f1f03465294a4ec7970f006bc80a15a7f4)