Check presence of fingerprint before normalising
Otherwise the following error is thrown, when fingerprint is nil:
> NoMethodError: undefined method `gsub' for nil:NilClass